<a href="https://colab.research.google.com/github/RegretCode/Desenvolvedor-Python-IGTI/blob/main/TrabalhoPraticoMd_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar as bibliotecas do numpy e pandas
import numpy as np
import pandas as pd

In [ ]:
# Executar/Completar os trechos de código a seguir para responder às
# questões objetivas. Complete-os de forma que o resultado da execução
# da função print seja igual ao da imagem correspondente:

# == CODIGO 1 == #
Z = np.zeros((4, ))
print("Z:", Z)

Z: [0. 0. 0. 0.]


In [ ]:
# == CODIGO 2 == #
Z = np.zeros((4, ))
Z[1] = 1
print("Z:", Z)

Z: [0. 1. 0. 0.]


In [ ]:
# == CODIGO 3 == #
Z = np.zeros((4, ))
Z[1:] = 1
print("Z:", Z)

Z: [0. 1. 1. 1.]


In [ ]:
# == CODIGO 4 == #
Z = np.ones((4, ))
Z [-1:]= 0
print("Z:", Z)

# #===================
# a = np.zeros((4, ))
# a[:3] = 1.
# print("a:", a)
# #===================
# b = np.ones((4,))
# b[-1] = 0.
# print("b:", b)
# #===================
# c = np.zeros((4, ))
# c[:-1] = 1.
# print("c:", c)
# #===================
# d = np.ones((4,))
# d[4] = 0. <-------------------- esse esta errado, index out of bounds
# print("d:", d)

Z: [1. 1. 1. 0.]


In [ ]:
# == CODIGO 5 == #
X = np.array([[2, 2], [2, 2]])
print("X:", X)

# #===================
# a = np.array([2.] * 4).reshape(2, 2)
# print("a:", a)
# #===================
# b = 2 * np.ones((2, 2))
# print("b:", b)
# #===================
# c = np.ones((2, 2)) + np.ones((2, 2))
# print("c:", c)
# #===================
# d = np.twos((2, 2)) <----------------- n existe np.twos
# print("c:", c)

X: [[2 2]
 [2 2]]


In [ ]:
# == CODIGO 6 == #
X = np.array([[1, 2], [3, 4]])
Y = X[0, :]
Y[1] = 10
print("X:\n", X)

X:
 [[ 1 10]
 [ 3  4]]


In [ ]:
# == CODIGO 7 == #
X = np.array([[1, 3], [11, 10]])
print(np.mean(X[X > np.pi]))  # np.mean eh uma funcao do NumPy que calcula a media dos vetores de um array ou ao longo de um determinado eixo.
                              # np.pi eh uma constante definida em NumPy que representa o valor de Pi

10.5


In [ ]:
# == CODIGO 8 == #
data  = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
         'age' : [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3], # np.nan == not an number
         'visits' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
         'priority' : ['yes' , 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

print(data)
print(labels)

{'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'], 'age': [2.5, 3, 0.5, nan, 5, 2, 4.5, nan, 7, 3], 'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
# == CODIGO 9 == #
df = pd.DataFrame(data=data, index=labels)
print(df)

#====================
# df.shape #atributo de df pode ser acessado para uma rápida verificação de sua dimensão (número de linhas, número de colunas)
# df['animal'].value_counts() #<---------- Retorna um pandas DataFrame contendo a contagem da quantidade de vezes que cada elemento único aparece na coluna ‘animal’.
# df.describe()
# df.sort_values(by='visits', ascending=False) #<- retorna um pandas DataFrame ordenado de forma decrescente baseado na coluna ‘visits’

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


In [ ]:
# == CODIGO 10 == #
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])

np.sqrt(((y_true-y_pred)**2).mean()) # calcula a raiz quadrada da média dos erros ao quadrado entre dois arrays: y_true e y_pred. Essa métrica é comumente usada para avaliar a diferença ou o erro entre valores previstos (y_pred) e valores reais (y_true).

[1. 2. 1.]
[1.1  1.98 1.05]


0.06557438524302006